import { TextureLoader } from "three";
import { useLoader } from "@react-three/fiber";

export function useTexture(url) {
  return useLoader(TextureLoader, url);
}

export const TEXTURES = {
  metalRusty: "https://threejs.org/examples/textures/hardwood2_diffuse.jpg",
  concrete: "https://threejs.org/examples/textures/concrete_diffuse.jpg",
  grass: "https://threejs.org/examples/textures/grass.jpg",
  epdm: "https://threejs.org/examples/textures/rubber.jpg",
  wood: "https://threejs.org/examples/textures/wood.jpg",
};

export const STAGES = [
  {
    id: "collecte", label: "01 · Collecte", title: "Collecte des déchets",
    text: "Les déchets organiques (fumier, déchets alimentaires, résidus agricoles) sont réunis comme matière première du processus de méthanisation.",
    color: "#B88955", position: [-20, 0, 0],
    temperature: "Ambiante",
    ph: "—",
    retentionTime: "—",
    equation: "Matière organique → Substrat brut",
    bacteria: "—",
    metrics: { capacity: "3 000 – 10 000 t/an", biogasYield: "~100–150 m³/t MS", substrates: "Fumier, MAR, résidus verts" },
    facts: [
      { label: "Substrats", value: "Fumier, MAR, résidus verts, lisiers" },
      { label: "Objectif", value: "Collecte et stockage temporaire" },
      { label: "Teneur MS", value: "8–20% matière sèche" },
      { label: "C/N optimal", value: "20–30 :1" },
    ],
  },
  {
    id: "tri", label: "02 · Réception / Tri", title: "Réception et tri",
    text: "Les éléments indésirables (pierres, sable, plastiques, produits chimiques) sont retirés manuellement ou mécaniquement pour protéger les équipements en aval.",
    color: "#B88955", position: [-12, 0, 0],
    temperature: "Ambiante",
    ph: "—",
    retentionTime: "—",
    equation: "Substrat brut → Substrat trié",
    bacteria: "—",
    metrics: { capacity: "~5 t/h", rejection: "5–15% du flux", equipment: "Tapis vibrant, broyeur" },
    facts: [
      { label: "Déchets retirés", value: "Pierres, métaux, plastiques" },
      { label: "Méthode", value: "Tri manuel + crible vibrant" },
      { label: "Débit horaire", value: "~5 tonnes/heure" },
      { label: "Taux de rejet", value: "5–15% du flux brut" },
    ],
  },
  {
    id: "pretraitement", label: "03 · Prétraitement", title: "Prétraitement",
    text: "Le substrat est broyé, mélangé et homogénéisé pour faciliter l'action des bactéries dans le méthaniseur. La granulométrie est réduite à < 10 mm.",
    color: "#C99A61", position: [-4, 0, 0],
    temperature: "Ambiante",
    ph: "6.5–7.5",
    retentionTime: "24–48h",
    equation: "Substrat trié → Substrat homogénéisé",
    bacteria: "—",
    metrics: { particleSize: "< 10 mm", power: "15–30 kW", mixingTime: "2–4 h" },
    facts: [
      { label: "Broyage", value: "Granulométrie < 10 mm" },
      { label: "Mélange", value: "Homogénéisation des substrats" },
      { label: "Puissance", value: "15–30 kW (broyeur)" },
      { label: "Dilution", value: "Ajout d'eau si nécessaire (10–12% MS)" },
    ],
  },
  {
    id: "methaniseur", label: "04 · Méthaniseur", title: "Digestion anaérobie",
    text: "Cœur du système : les micro-organismes décomposent la matière organique en absence d'oxygène, en maintenant 35–37°C (régime mésophile) pendant 20–40 jours.",
    color: "#68B58C", position: [4, 0, 0],
    temperature: "35–37°C (mésophile)",
    ph: "6.8–7.2",
    retentionTime: "20–40 jours",
    equation: "Matière organique → CH₄ + CO₂ + digestat",
    bacteria: "Bactéries anaérobies (Clostridium, Methanobacterium, Methanosarcina)",
    metrics: { volume: "500–2 000 m³", pressure: "10–30 mbar", gasProduction: "~120 m³ biogaz/t MS" },
    facts: [
      { label: "Volume cuve", value: "500–2 000 m³" },
      { label: "Température", value: "35–37°C (mésophile) ou 52–55°C (thermophile)" },
      { label: "Pression", value: "10–30 mbar sous dôme EPDM" },
      { label: "Rendement", value: "~120 m³ biogaz / tonne MS" },
    ],
  },
  {
    id: "hydrolyse", label: "04a · Hydrolyse", title: "Hydrolyse",
    text: "Les bactéries hydrolytiques (Clostridium, Bacteroides) décomposent les polymères complexes (glucides, protéines, lipides) en monomères assimilables par les bactéries suivantes.",
    color: "#C99A61", position: [4, 0, 0],
    temperature: "35–37°C (mésophile)",
    ph: "6.5–7.0",
    retentionTime: "5–10 jours",
    equation: "(C₆H₁₀O₅)ₙ + nH₂O → nC₆H₁₂O₆",
    bacteria: "Clostridium, Bacteroides, Streptococcus",
    metrics: { speed: "Étape limitante", efficiency: "40–60% conversion", enzymes: "Cellulases, protéases, lipases" },
    facts: [
      { label: "Réaction", value: "(C₆H₁₀O₅)ₙ + nH₂O → nC₆H₁₂O₆" },
      { label: "Bactéries", value: "Clostridium, Bacteroides" },
      { label: "Substrats", value: "Glucides, protéines, lipides" },
      { label: "Importance", value: "Étape limitante du processus" },
    ],
  },
  {
    id: "acidogenese", label: "04b · Acidogenèse", title: "Acidogenèse",
    text: "Les bactéries acidogènes transforment les monomères en acides gras volatils (AGV), alcools, CO₂ et H₂. Phase de production acide intense.",
    color: "#D88961", position: [4, 0, 0],
    temperature: "35–37°C (mésophile)",
    ph: "5.5–6.5",
    retentionTime: "3–5 jours",
    equation: "C₆H₁₂O₆ → 2CH₃COOH + 2CO₂ + 2H₂",
    bacteria: "Clostridium, Escherichia coli, Streptococcus",
    metrics: { pH: "5.5–6.5 (phase acide)", agv: "2–5 g/L", speed: "Rapide (1–3 jours)" },
    facts: [
      { label: "Réaction", value: "C₆H₁₂O₆ → 2CH₃COOH + 2CO₂ + 2H₂" },
      { label: "Produits", value: "Acides gras volatils (propionique, butyrique)" },
      { label: "pH", value: "5.5–6.5 (phase acide)" },
      { label: "Bactéries", value: "Clostridium, E. coli" },
    ],
  },
  {
    id: "acetogenese", label: "04c · Acétogenèse", title: "Acétogenèse",
    text: "Les bactéries acétogènes convertissent les acides gras volatils et les alcools en acétate, H₂ et CO₂ — substrats directs pour les productrices de méthane.",
    color: "#B7C66D", position: [4, 0, 0],
    temperature: "35–37°C (mésophile)",
    ph: "6.5–7.0",
    retentionTime: "2–3 jours",
    equation: "AGV + Alcools → CH₃COOH + H₂ + CO₂",
    bacteria: "Syntrophomonas, Syntrophobacter",
    metrics: { acetate: "1–4 g/L", synergy: "Obligatoire avec méthanogènes", pH: "6.5–7.0" },
    facts: [
      { label: "Réaction", value: "CH₃CH₂COOH → CH₃COOH + CO₂ + H₂" },
      { label: "Bactéries", value: "Syntrophomonas (symbiose obligatoire)" },
      { label: "Condition", value: "Pression partielle H₂ < 10⁻⁴ atm" },
      { label: "Rôle", value: "Précurseur direct du méthane" },
    ],
  },
  {
    id: "methanogenese", label: "04d · Méthanogenèse", title: "Méthanogenèse",
    text: "Les archées méthanogènes produisent CH₄ (méthane) par deux voies : acétoclastique (acétate → CH₄ + CO₂) et hydrogénotrope (CO₂ + 4H₂ → CH₄ + 2H₂O).",
    color: "#D8A93E", position: [4, 0, 0],
    temperature: "35–37°C (mésophile)",
    ph: "6.8–7.2",
    retentionTime: "10–20 jours",
    equation: "CH₃COOH → CH₄ + CO₂  |  CO₂ + 4H₂ → CH₄ + 2H₂O",
    bacteria: "Methanosarcina, Methanobacterium, Methanosaeta",
    metrics: { ch4: "50–75% du biogaz", speed: "Lente (étape limitante)", yield: "~350 L CH₄/kg VS" },
    facts: [
      { label: "Voie acétoclastique", value: "CH₃COOH → CH₄ + CO₂ (70%)" },
      { label: "Voie hydrogénotrope", value: "CO₂ + 4H₂ → CH₄ + 2H₂O (30%)" },
      { label: "Archées", value: "Methanosarcina, Methanosaeta" },
      { label: "Rendement", value: "~350 L CH₄/kg MATIERE VOLATILE" },
    ],
  },
  {
    id: "traitement_biogaz", label: "05 · Traitement du biogaz", title: "Épuration et stockage",
    text: "Le biogaz brut (CH₄ + CO₂ + H₂S + H₂O) est épuré : les sulfures d'hydrogène (H₂S) et le CO₂ sont partiellement éliminés avant stockage sous dôme EPDM à faible pression.",
    color: "#D8A93E", position: [12, 0, 0],
    temperature: "Ambiante",
    ph: "—",
    retentionTime: "Stockage : 1–7 jours",
    equation: "Biogaz brut → Biogaz épuré (↑ CH₄ %)",
    bacteria: "—",
    metrics: { ch4: "50–75% → 55–80% après épuration", h2s: "< 200 ppm", pressure: "Quelques mbar" },
    facts: [
      { label: "Épuration H₂S", value: "Filtration ferrique ou bioréparation" },
      { label: "Stockage", value: "Dôme EPDM souple à faible pression" },
      { label: "Pression", value: "5–30 mbar" },
      { label: "Débit", value: "100–3 000 m³/h selon la taille" },
    ],
  },
  {
    id: "cogeneration", label: "06 · Cogénération", title: "Production d'énergie",
    text: "Le biogaz alimente un moteur à combustion interne couplé à un alternateur. La cogénération produit simultanément électricité (35%) et chaleur (65%) valorisée en chauffage ou séchage.",
    color: "#DE7248", position: [20, 0, 0],
    temperature: "~400°C (température moteur)",
    ph: "—",
    retentionTime: "—",
    equation: "CH₄ + 2O₂ → CO₂ + 2H₂O + Énergie",
    bacteria: "—",
    metrics: { power: "100–500 kWe", heat: "150–850 kWth", efficiency: "35% élec / 65% thermique" },
    facts: [
      { label: "Puissance", value: "100–500 kWe (selon taille)" },
      { label: "Rendement électrique", value: "35% → électricité injectée" },
      { label: "Rendement thermique", value: "65% → chaleur récupérée" },
      { label: "Consommation", value: "~6 000 m³ biogaz/MWh" },
    ],
  },
  {
    id: "separation_phases", label: "07 · Séparation de phases", title: "Traitement du digestat",
    text: "Le digestat sorti du méthaniseur est séparé par vis extrudeuse en phase solide (compost, paillage) et phase liquide (liquide riche en azote, épandage agricole).",
    color: "#58C993", position: [28, 0, 0],
    temperature: "35°C",
    ph: "7.5–8.5",
    retentionTime: "—",
    equation: "Digestat → Phase solide + Phase liquide",
    bacteria: "—",
    metrics: { solidFraction: "30–40% DS", liquidFraction: "60–70%", compostQuality: "C/N < 20, pH 7–8" },
    facts: [
      { label: "Phase solide", value: "30–40% → compost / paillage / litière" },
      { label: "Phase liquide", value: "60–70% → engrais azoté liquide" },
      { label: "Azote total", value: "3–5 g/L (phase liquide)" },
      { label: "Méthode", value: "Séparateur à vis (screw press)" },
    ],
  },
  {
    id: "torchere", label: "08 · Torchère", title: "Sécurité — Torchère",
    text: "En cas de surproduction de biogaz ou de maintenance, la torchère brûle le excédent de CH₄ en toute sécurité, évitant les rejets directs de méthane (GWP = 28× CO₂).",
    color: "#FF5722", position: [36, 0, 0],
    temperature: "~1 000°C (flamme)",
    ph: "—",
    retentionTime: "Continu (sécurité)",
    equation: "CH₄ + 2O₂ → CO₂ + 2H₂O (combustion complète)",
    bacteria: "—",
    metrics: { flameTemp: "~1 000°C", capacity: "Jusqu'à 100% du débit", purpose: "Sécurité uniquement" },
    facts: [
      { label: "Fonction", value: "Brûler l'excédent de biogaz" },
      { label: "Déclencheur", value: "Maintenance ou surproduction" },
      { label: "Impact", value: "CH₄ → CO₂ (GWP ×28 réduit)" },
      { label: "Norme", value: "ATEX / EN 1127-1" },
    ],
  },
  {
    id: "controle", label: "09 · Contrôle", title: "Bâtiment de contrôle — SCADA",
    text: "Le centre de supervision SCADA (Supervisory Control and Data Acquisition) pilote l'ensemble de l'installation en temps réel : température, pression, débit, pH, composition du biogaz.",
    color: "#3B82F6", position: [0, 0, 12],
    temperature: "~22°C (salle serveurs)",
    ph: "—",
    retentionTime: "—",
    equation: "Supervision continue de tous les capteurs",
    bacteria: "—",
    metrics: { sensors: "50–200 capteurs", refreshRate: "1–5 s", alertSystem: "SMS/email automatique" },
    facts: [
      { label: "Système", value: "SCADA — Supervision automatisée" },
      { label: "Capteurs", value: "50–200 points de mesure" },
      { label: "Paramètres", value: "T°, P, pH, débit, CH₄%, H₂S" },
      { label: "Alertes", value: "SMS/email en temps réel" },
    ],
  },
];
